git --git-dir=$HOME/Linux/dotfiles/ --work-tree=$HOME add \
~/.config/fish/config.fish \
~/.config/fish/fish_variables \
~/.config/python/pythonrc \
~/.config/user-dirs.dirs \
~/.gitconfig \
~/.local/scripts/* \
~/.config/alacritty/alacritty.yml \
~/.config/celluloid/scripts/* \
~/.config/FreeTube/profiles.db \
~/.config/mpd/mpd.conf \
~/.config/ncmpcpp/config \
~/.config/mpv/mpv.conf \
~/.config/picom/picom.conf \
~/.config/polybar/* \
~/.config/qtile/config.py \
~/.config/rofi/* \
~/.config/yt-dlp/config \
~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml \
~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml \
~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml \
~/.config/easyeffects/autoload/output/* \
~/.config/easyeffects/output/* \
~/Media/Images/Wallpaper.jpg \
~/Linux/slick-greeter.conf \
~/Linux/git-add.sh \
~/Linux/fedora.sh \
~/.config/nvim/init.vim \
~/.config/zsh/zsh-vim-mode.plugin.zsh \
~/.config/zsh/zsh-history-substring-search.zsh \
~/.local/share/fonts/* \
~/.local/share/themes/* \
~/.config/Code/User/settings.json \
~/Linux/code.desktop \
~/Linux/disable_usb_wakeup.conf
